### ISSUE TITLE
Sprite expressions:  ImageWidthScale / ImageHeightScale

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#176] opened 2024-03-12 10:12 UTC
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add `ImageWidthScale` and `ImageHeightScale` expression for Sprite obejct

This is a discussion going back 10 years.
https://www.construct.net/en/forum/construct-2/general-discussion-17/suggestion-compare-scale-72042
https://www.construct.net/en/forum/construct-2/general-discussion-17/why-isnt-scale-expression-82792

### Possible workarounds or alternatives

Currently this scale value can only be calculated manually.
```
Sprite.Width / Sprite.ImageWidth
Sprite.Height / Sprite.ImageHeight
```

### Proposed solution

Add `ImageWidthScale` and `ImageHeightScale` expression

### Why is this idea important?

Let developers reduce some boring math troubles and improve some quality of life.

I think this value is already present in the runtime, it's just not exposed. Because when we use Tween, we can select the X Scale property

**Comment by AshleyScirra** [comment] 2024-04-04 16:08
This appears to be a duplicate of #152.

**Closed by AshleyScirra** 2024-04-04 16:08 UTC
Labels: duplicate
