### ISSUE TITLE
Save and Load color palette information in sprite editor

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-feature-requests#306] opened 2024-06-24 15:30 UTC
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

It would be awesome if there was a way to export and import color palette so it can be imported and reused in different projects

![image](https://github.com/Scirra/Construct-feature-requests/assets/7579560/61d5b7de-5c9f-4443-94b9-bb75750101ce)

Setting up a color palette is time consuming. and is frequently reused. 

being able to import industry standard palette file types would also be good, as long as there is a way to import/export the colors 

you can find several palette file types here as an example : https://lospec.com/palette-list/star3a28

(.pal, .ase, .hex, .txt) also being able to generate a palette from a sprite would also solve this issue. 

### Possible workarounds or alternatives

manually import a sprite with all the colors, use the color picker to pick each color, and save the color the current editor (super tedious for lots of colors)

### Proposed solution

there are many viable solutions, I will detail them below, any of these solutions would work.

-  add an import/export button to the animation editor, the export will download a file that contains color information,,, that same file that was produced by the export can them be imported, this will overwrite all the current colors in the animations editor and restore to the state of when it was export so all the colors would be there.

 - add just an import button, this will open a file dialog where the user can import one of the standard color palette file types (.pal, .ase, .hex, .txt), this will replace all the colors in the animation editor with the ones described in the file
 
 - add a button to generate a color palette from the current sprite frame in the animation editor, this will traverse the sprites pixel data, and produce a list of unique colors in the animation editor color section. 

### Why is this idea important?

this will save a lots of times if you are using the animation editor to make changes to sprites. it is a much-welcomed QOL improvement

**Comment by Pigpud** [comment] 2024-06-24 15:59
We need this!

**Comment by DiegoScirra** [comment] 2024-06-24 16:40
Duplicate of #178. Closing. Up vote the other one if you haven't already.

**Closed by DiegoScirra** 2024-06-24 16:40 UTC
Labels: duplicate
